version: "3.5"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - proxynet

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - proxynet

  producer1:
    build: ../../producer
    container_name: producer1
    tty: true
    links:
      - rabbitmq
      - mysql
    networks:
      - proxynet

  producer2:
    build: ../../producer
    container_name: producer2
    tty: true
    links:
      - rabbitmq
      - mysql
    networks:
      - proxynet

  loadbalancer:
    build: ./load-balancer
    container_name: loadbalancer
    tty: true
    links:
      - producer1
      - producer2
    ports:
      - 8080:8080
    networks:
      - proxynet

#  consumer1:
#    build: ../../consumer
#    container_name: consumer1
#    tty: true
#    links:
#      - rabbitmq
#    networks:
#      - proxynet
#
#  consumer2:
#    build: ../../consumer
#    container_name: consumer2
#    tty: true
#    links:
#      - rabbitmq
#    networks:
#      - proxynet

networks:
  proxynet:
    driver: "bridge"